apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-nginx-dev
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/EnsarTopal/platform-gitops.git
    targetRevision: HEAD
    path: apps/demo-nginx/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  ignoreDifferences:
    - group: argoproj.io
      kind: AnalysisTemplate
      jsonPointers:
        - /spec/metrics/0/successCondition
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
