apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform managed by GitOps
  sourceRepos:
  - https://github.com/EnsarTopal/platform-gitops.git
  - https://kubernetes.github.io/ingress-nginx
  - https://metallb.github.io/metallb
  destinations:
  - namespace: "*"
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
