apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager/kustomization.yaml
  - metallb-config.yaml
  - external-secrets/kustomization.yaml
  - kyverno/policies.yaml
  - harbor/kustomization.yaml
