apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: nginx-error-rate
  namespace: demo
spec:
  metrics:
  - name: error-rate
    interval: 30s
    count: 3
    failureLimit: 2
    provider:
      prometheus:
        address: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        query: |
          sum(rate(nginx_ingress_controller_requests{status=~"5.."}[2m])) or vector(0)
        successCondition: "len(result) == 0 || result[0] <= 0.05"
