apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: nginx-error-rate
spec:
  metrics:
    - name: error-rate
      interval: 30s
      count: 3
      failureLimit: 1
      initialDelay: 30s
      provider:
        prometheus:
          address: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
          query: |
            sum(
              rate(
                nginx_ingress_controller_requests{
                  status=~"5..",
                  exported_namespace="demo"
                }[2m]
              )
            ) or vector(0)
      successCondition: "result[0] <= 0.05"
      failureCondition: "result[0] > 0.05"
