apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: nginx-error-rate
  namespace: demo
spec:
  metrics:
  - name: error-rate
    interval: 30s
    count: 3
    successCondition: result[0] <= 0.05
    failureLimit: 1
    provider:
      prometheus:
        address: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        query: |
          scalar(
            sum(rate(nginx_ingress_controller_requests{status=~"5.."}[2m])) /
            (sum(rate(nginx_ingress_controller_requests[2m])) > 0)
            or vector(0)
          )
