apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: html
        configMap:
          name: nginx-html
          items:
          - key: index.html
            path: index.html
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
  strategy:
    canary:
      canaryService: nginx-canary
      stableService: nginx
      trafficRouting:
        nginx:
          stableIngress: nginx
      steps:
      - setWeight: 20
      - pause: {}
      - analysis:
          templates:
          - templateName: nginx-error-rate
      - setWeight: 50
      - pause: {duration: 30s}
      - setWeight: 100
