apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: argocd-server-pdb
  namespace: argocd
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: argocd-repo-server-pdb
  namespace: argocd
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: grafana-pdb
  namespace: monitoring
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/instance: monitoring
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ingress-nginx-controller-pdb
  namespace: ingress-nginx
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: harbor-core-pdb
  namespace: harbor
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: harbor
      component: core
      release: infra-harbor
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: harbor-portal-pdb
  namespace: harbor
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: harbor
      component: portal
      release: infra-harbor
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: harbor-registry-pdb
  namespace: harbor
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: harbor
      component: registry
      release: infra-harbor
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: harbor-jobservice-pdb
  namespace: harbor
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: harbor
      component: jobservice
      release: infra-harbor
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: minio-pdb
  namespace: minio
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app: minio
