apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: pex-harbor-trivy
  namespace: kyverno
spec:
  exceptions:
    - policyName: disallow-root-user
      ruleNames:
        - check-root-user
        - autogen-check-root-user
  match:
    any:
      - resources:
          kinds:
            - Pod
          namespaces:
            - harbor
          selector:
            matchExpressions:
              - key: component
                operator: In
                values: ["trivy"]
              - key: app
                operator: In
                values: ["harbor"]
