apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-root-user
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: check-root-user
    match:
      any:
      - resources:
          kinds: [Pod]
    exclude:
      any:
      - resources:
          namespaces: [kube-system, kyverno, longhorn-system, monitoring]
    validate:
      message: "Containers must not run as root. Set runAsNonRoot: true."
      anyPattern:
      - spec:
          securityContext:
            runAsNonRoot: true
      - spec:
          containers:
          - securityContext:
              runAsNonRoot: true
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-privilege-escalation
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: check-privilege-escalation
    match:
      any:
      - resources:
          kinds: [Pod]
    exclude:
      any:
      - resources:
          # argo-rollouts dashboard henuz upstream'de duzeltilmemis:
          # https://github.com/argoproj/argo-rollouts/issues/3127
          namespaces: [kube-system, kyverno, longhorn-system, monitoring, argo-rollouts]
    validate:
      message: "allowPrivilegeEscalation must be set to false."
      pattern:
        spec:
          containers:
          - securityContext:
              allowPrivilegeEscalation: false
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-resource-limits
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: check-resource-limits
    match:
      any:
      - resources:
          kinds: [Pod]
    exclude:
      any:
      - resources:
          namespaces: [kube-system, kyverno, longhorn-system, cert-manager, monitoring]
    validate:
      message: "CPU and memory limits are required for all containers."
      pattern:
        spec:
          containers:
          - resources:
              limits:
                cpu: "?*"
                memory: "?*"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-host-namespaces
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: host-namespaces
    match:
      any:
      - resources:
          kinds: [Pod]
    exclude:
      any:
      - resources:
          namespaces: [kube-system, kyverno, longhorn-system]
    validate:
      message: "Host network, PID, and IPC namespaces are not allowed."
      pattern:
        spec:
          =(hostNetwork): false
          =(hostPID): false
          =(hostIPC): false
