apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-dev
spec:
  template:
    spec:
      containers:
      - name: nginx
        image: harbor.lab.local/library/nginx-unprivileged:1.27
