apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-external-secrets-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform
  source:
    repoURL: https://github.com/EnsarTopal/platform-gitops.git
    targetRevision: HEAD
    path: clusters/work/infra/config/external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring    # default namespace — ExternalSecret'lar kendi namespace'ini tanımlıyor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true   # cross-namespace kaynaklar için gerekli
