apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-gitea
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  source:
    chart: gitea
    repoURL: https://dl.gitea.com/charts/
    targetRevision: 12.5.0
    helm:
      releaseName: gitea
      values: |-
        global:
          security:
            allowInsecureImages: true
        image:
          registry: harbor.lab.local
          repository: library/gitea
          tag: 1.25.4-rootless
          rootless: true
        gitea:
          admin:
            username: gitea_admin
            password: "Gitea12345!"
            email: "admin@lab.local"
          config:
            server:
              DOMAIN: gitea.lab.local
              ROOT_URL: https://gitea.lab.local
            webhook:
              ALLOWED_HOST_LIST: "*"
        podSecurityContext:
          runAsNonRoot: true
          runAsUser: 1000
          fsGroup: 1000
        containerSecurityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: selfsigned-issuer
          hosts:
            - host: gitea.lab.local
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: gitea-tls
              hosts:
                - gitea.lab.local
        persistence:
          enabled: true
          size: 5Gi
        postgresql-ha:
          enabled: false
        postgresql:
          enabled: true
          image:
            registry: harbor.lab.local
            repository: library/postgresql
            tag: 17.6.0-debian-12-r4
          primary:
            persistence:
              size: 5Gi
        valkey-cluster:
          enabled: true
          image:
            registry: harbor.lab.local
            repository: library/valkey-cluster
            tag: 8.1.3-debian-12-r3
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
