apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-gitea
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  source:
    chart: gitea
    repoURL: https://dl.gitea.com/charts/
    targetRevision: 12.5.0
    helm:
      releaseName: gitea
      values: |-
        gitea:
          admin:
            password: "Gitea12345!"
          config:
            database:
              DB_TYPE: postgres
              HOST: gitea-postgresql:5432

        # Kyverno Fix: Tüm init containerlara kaynak limiti tanımlıyoruz
        initContainers:
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi

        postgresql:
          enabled: true
          primary:
            persistence:
              storageClass: longhorn

        valkey-cluster:
          enabled: true
          master:
            disableAof: true
          persistence:
            storageClass: longhorn
