apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-harbor
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.14.2
    helm:
      releaseName: infra-harbor
      values: |
        expose:
          type: nodePort
          tls:
            enabled: true
          nodePort:
            ports:
              http:
                port: 80
                nodePort: 30080
              https:
                port: 443
                nodePort: 30443

        # Ingress kapansın (nodePort kullanacağız)
        ingress:
          enabled: false

        # Harbor external URL (UI için düzgün link üretir)
        externalURL: https://harbor.lab.local:30443
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
