apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-harbor
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.14.2
    helm:
      releaseName: infra-harbor
      values: |
        expose:
          type: ingress
          tls:
            enabled: true
            certSource: secret
            secret:
              secretName: harbor-tls
          ingress:
            hosts:
              core: harbor.lab.local
            annotations:
              kubernetes.io/ingress.class: nginx
              cert-manager.io/cluster-issuer: lab-ca-issuer
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
              nginx.ingress.kubernetes.io/proxy-body-size: "0"
        externalURL: https://harbor.lab.local
        caSecretName: ""
        containerSecurityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
        core:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
        jobservice:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
        registry:
          registry:
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi
          controller:
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 250m
                memory: 256Mi
        portal:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
        database:
          internal:
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi
        redis:
          internal:
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 250m
                memory: 256Mi
        trivy:
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
        persistence:
          persistentVolumeClaim:
            registry:
              storageClass: "longhorn"
              size: 5Gi
            jobservice:
              jobLog:
                storageClass: "longhorn"
                size: 1Gi
            database:
              storageClass: "longhorn"
              size: 1Gi
            redis:
              storageClass: "longhorn"
              size: 1Gi
            trivy:
              storageClass: "longhorn"
              size: 5Gi
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
