apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-harbor
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.14.2
    helm:
      releaseName: infra-harbor
      values: |
        expose:
          type: ingress
          tls:
            enabled: true
            certSource: secret
            secret:
              secretName: harbor-tls
          ingress:
            hosts:
              core: harbor.lab.local
            annotations:
              kubernetes.io/ingress.class: nginx
              cert-manager.io/cluster-issuer: lab-ca-issuer
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
              nginx.ingress.kubernetes.io/proxy-body-size: "0"
        externalURL: https://harbor.lab.local
        persistence:
          persistentVolumeClaim:
            registry:
              storageClass: "longhorn"
              size: 5Gi
            jobservice:
              jobLog:
                storageClass: "longhorn"
                size: 1Gi
            database:
              storageClass: "longhorn"
              size: 1Gi
            redis:
              storageClass: "longhorn"
              size: 1Gi
            trivy:
              storageClass: "longhorn"
              size: 5Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
