apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-kyverno
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://kyverno.github.io/kyverno
    chart: kyverno
    targetRevision: 3.2.6
    helm:
      releaseName: kyverno
      values: |
        crds:
          install: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  ignoreDifferences:
    - group: batch
      kind: CronJob
      namespace: kyverno
      jsonPointers:
        - /spec
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
