apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-kyverno
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://kyverno.github.io/kyverno
    chart: kyverno
    targetRevision: 3.2.6
    helm:
      releaseName: kyverno
      values: |
        crds:
          install: true

        # --- IMPORTANT: disable kubectl-based hooks/jobs because docker.io/registry.k8s.io is blocked ---
        # post-upgrade hook job: kyverno-clean-reports
        policyReportsCleanup:
          enabled: false

        # post-upgrade migration hook (can also rely on kubectl image)
        migration:
          enabled: false

        # pre-delete hook jobs (scale-to-zero, remove-configmap, webhook cleanup)
        webhooksCleanup:
          enabled: false

        # cleanup cronjobs which use kubectl image (bitnami/kubectl by default)
        cleanupJobs:
          admissionReports:
            enabled: false
          clusterAdmissionReports:
            enabled: false
          ephemeralReports:
            enabled: false
          clusterEphemeralReports:
            enabled: false
          updateRequests:
            enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
