apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-kyverno
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://kyverno.github.io/kyverno
    chart: kyverno
    targetRevision: 3.2.6
    helm:
      releaseName: kyverno
      values: |
        crds:
          install: true

        # --- FIX: disable Helm hooks/jobs which require pulling kubectl images ---
        # This disables the post-upgrade hook job "kyverno-clean-reports"
        policyReportsCleanup:
          enabled: false

        # This disables the cleanup cronjobs (cleanup-* reports/updateRequests)
        cleanupJobs:
          admissionReports:
            enabled: false
          clusterAdmissionReports:
            enabled: false
          ephemeralReports:
            enabled: false
          clusterEphemeralReports:
            enabled: false
          updateRequests:
            enabled: false

        # Optional: also disable other hook-like jobs if present in this chart version
        webhooksCleanup:
          enabled: false
        migration:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
