apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-loki
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.16.0
    helm:
      releaseName: loki
      parameters:
        - name: loki.useTestSchema
          value: "true"
        - name: ingress.enabled
          value: "false"
        - name: gateway.ingress.enabled
          value: "false"
      values: |
        deploymentMode: SingleBinary

        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem

        singleBinary:
          replicas: 1
          persistence:
            enabled: false

        read:
          replicas: 0
        write:
          replicas: 0
        backend:
          replicas: 0

        gateway:
          enabled: true
          service:
            type: ClusterIP
