apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-loki
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.16.0
    helm:
      releaseName: loki
      values: |
        deploymentMode: SingleBinary

        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
          schemaConfig:
            configs:
              - from: "2024-01-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: index_
                  period: 24h

        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            size: 5Gi

        read:
          replicas: 0
        write:
          replicas: 0
        backend:
          replicas: 0

        gateway:
          enabled: true
          service:
            type: ClusterIP

        ingress:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
