apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-loki
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.16.0
    helm:
      releaseName: loki
      parameters:
        - name: loki.useTestSchema
          value: "true"
      values: |
        deploymentMode: SingleBinary

        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem

        singleBinary:
          replicas: 1
          persistence:
            enabled: false

        read:
          replicas: 0
        write:
          replicas: 0
        backend:
          replicas: 0

        gateway:
          enabled: true
          ingress:
            enabled: false
          service:
            type: ClusterIP

        ingress:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
