apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-loki
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.16.0
    helm:
      releaseName: loki
      values: |
        loki:
          auth_enabled: false

        # Single-binary (homelab için kolay)

        singleBinary:
          replicas: 1
          persistence:
            enabled: false

        # dev/test için memory storage (PVC yok)
        loki:
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem

        gateway:
          enabled: true
          service:
            type: ClusterIP

        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - host: loki.lab.local
              paths:
                - path: /
                  pathType: Prefix
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
