apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-longhorn
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.6.2
    helm:
      releaseName: longhorn
      values: |
        preUpgradeChecker:
          jobEnabled: false
        defaultSettings:
          defaultReplicaCount: 2
          storageMinimalAvailablePercentage: 15
          defaultDataPath: /var/lib/longhorn
        ingress:
          enabled: true
          ingressClassName: nginx
          host: longhorn.lab.local
          annotations:
            cert-manager.io/cluster-issuer: lab-ca-issuer
          tls: true
          tlsSecret: longhorn-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
