apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-minio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: platform
  source:
    repoURL: https://github.com/EnsarTopal/platform-gitops.git
    targetRevision: HEAD
    path: clusters/work/infra/config/minio
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
