apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-monitoring
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 56.6.2
    helm:
      releaseName: monitoring
      values: |
        grafana:
          adminPassword: "admin123"
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: lab-ca-issuer
            hosts:
              - grafana.lab.local
            tls:
              - secretName: grafana-tls
                hosts:
                  - grafana.lab.local
            path: /
            pathType: Prefix
          additionalDataSources:
            - name: Loki
              type: loki
              url: http://loki:3100
              access: proxy
              isDefault: false
        prometheus:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: lab-ca-issuer
            hosts:
              - prometheus.lab.local
            tls:
              - secretName: prometheus-tls
                hosts:
                  - prometheus.lab.local
            paths:
              - /
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
