apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-tekton-pipelines
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines
  source:
    repoURL: https://github.com/EnsarTopal/platform-gitops.git
    targetRevision: HEAD
    path: clusters/work/infra/config/tekton
    directory:
      include: "pipelines.yaml"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-tekton-triggers
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines
  source:
    repoURL: https://github.com/EnsarTopal/platform-gitops.git
    targetRevision: HEAD
    path: clusters/work/infra/config/tekton
    directory:
      include: "{triggers.yaml,interceptors.yaml}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
