apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
  namespace: tekton-ci
spec:
  params:
    - name: url
      type: string
    - name: revision
      type: string
      default: main
  workspaces:
    - name: output
  steps:
    - name: clone
      image: alpine/git:2.45.2
      env:
        - name: HOME
          value: /tekton/home
      securityContext:
        runAsUser: 0
      script: |
        #!/bin/sh
        set -eux
        mkdir -p /workspace/output
        rm -rf /workspace/output/source
        git config --global http.sslVerify false
        git clone "$(params.url)" /workspace/output/source
        cd /workspace/output/source
        git checkout "$(params.revision)"
