apiVersion: v1
kind: Secret
metadata:
  name: harbor-credentials
  namespace: tekton-ci
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{"harbor.lab.local":{"auth":"YWRtaW46bm1jMjc1V1hxTDhoYzZ6YQ=="}}}'
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-credentials
  namespace: tekton-ci
  annotations:
    tekton.dev/git-0: https://gitea.lab.local
type: kubernetes.io/basic-auth
stringData:
  username: gitea_admin
  password: "Gitea12345!"
