apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
  namespace: tekton-ci
spec:
  params:
    - name: url
      type: string
    - name: revision
      type: string
      default: main
  workspaces:
    - name: output
  steps:
    - name: clone
      image: alpine/git:2.45.2
      env:
        - name: HOME
          value: /tekton/home
      securityContext:
        runAsUser: 0
      script: |
        #!/bin/sh
        set -eux
        mkdir -p /workspace/output
        rm -rf /workspace/output/source
        git config --global http.sslVerify false
        git clone "$(params.url)" /workspace/output/source
        cd /workspace/output/source
        git checkout "$(params.revision)"
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: kaniko-build
  namespace: tekton-ci
spec:
  params:
    - name: image
      type: string
    - name: tag
      type: string
  workspaces:
    - name: source
  volumes:
    - name: docker-config
      secret:
        secretName: harbor-credentials
        items:
          - key: .dockerconfigjson
            path: config.json
  steps:
    - name: build-push
      image: harbor.lab.local/library/kaniko:latest
      args:
        - --dockerfile=$(workspaces.source.path)/source/Dockerfile
        - --context=$(workspaces.source.path)/source
        - --destination=$(params.image):$(params.tag)
        - --skip-tls-verify
        - --cache=false
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: update-gitops
  namespace: tekton-ci
spec:
  params:
    - name: image-tag
      type: string
    - name: gitops-repo
      type: string
      default: https://gitea.lab.local/gitea_admin/platform-gitops.git
  steps:
    - name: update-image
      image: alpine/git:2.45.2
      env:
        - name: HOME
          value: /tekton/home
        - name: GITEA_TOKEN
          valueFrom:
            secretKeyRef:
              name: gitea-credentials
              key: password
      securityContext:
        runAsUser: 0
      script: |
        #!/bin/sh
        set -eux
        git config --global http.sslVerify false
        git config --global user.email "tekton@lab.local"
        git config --global user.name "Tekton CI"

        REPO_URL=$(echo "$(params.gitops-repo)" | sed "s|https://|https://gitea_admin:${GITEA_TOKEN}@|")
        rm -rf /workspace/gitops
        git clone "${REPO_URL}" /workspace/gitops
        cd /workspace/gitops

        sed -i "s|value: harbor.lab.local/library/nginx-unprivileged:.*|value: harbor.lab.local/library/nginx-unprivileged:$(params.image-tag)|" \
          apps/demo-nginx/overlays/dev/kustomization.yaml

        git add apps/demo-nginx/overlays/dev/kustomization.yaml
        git commit -m "ci: update demo-nginx image to $(params.image-tag)"
        git push
