apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: []

patches:
  - path: patch-core.yaml
  - path: patch-jobservice.yaml
  - path: patch-portal.yaml
  - path: patch-registry.yaml
  - path: patch-database.yaml
  - path: patch-redis.yaml
  - path: patch-trivy.yaml
