apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-harbor-jobservice
  namespace: harbor
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: jobservice
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
