apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-harbor-portal
  namespace: harbor
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: portal
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
