apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: infra-harbor-redis
  namespace: harbor
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: redis
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
