resources:
  - ../../base
nameSuffix: -prod
commonLabels:
  env: prod
  team: devops
patches:
  - target:
      kind: Ingress
      name: nginx
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: demo-nginx-prod.lab.local
      - op: replace
        path: /spec/tls/0/hosts/0
        value: demo-nginx-prod.lab.local
      - op: replace
        path: /spec/tls/0/secretName
        value: nginx-prod-tls
